INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (1, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (2, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (3, 'Scarf', 'Official club scarf merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (4, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (5, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (6, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (7, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (8, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (9, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (10, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (11, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (12, 'Scarf', 'Official club scarf merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (13, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (14, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (15, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (16, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (17, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (18, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (19, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (20, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (21, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (22, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (23, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (24, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (25, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (26, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (27, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (28, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (29, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (30, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (31, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (32, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (33, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (34, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (35, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (36, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (37, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (38, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (39, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (40, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (41, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (42, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (43, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (44, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (45, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (46, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (47, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (48, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (49, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (50, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (51, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (52, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (53, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (54, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (55, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (56, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (57, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (58, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (59, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (60, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (61, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (62, 'Wristband', 'Official club athletic wristband', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (63, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (64, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (65, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (66, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (67, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (68, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (69, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (70, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (71, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (72, 'Cushion', 'Official club cushion merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (73, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (74, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (75, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (76, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (77, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (78, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (79, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (80, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (81, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (82, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (83, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (84, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (85, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (86, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (87, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (88, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (89, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (90, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (91, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (92, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (93, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (94, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (95, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (96, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (97, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (98, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (99, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (100, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (101, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (102, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (103, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (104, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (105, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (106, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (107, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (108, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (109, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (110, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (111, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (112, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (113, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (114, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (115, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (116, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (117, 'Scarf', 'Official club scarf merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (118, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (119, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (120, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (121, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (122, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (123, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (124, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (125, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (126, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (127, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (128, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (129, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (130, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (131, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (132, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (133, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (134, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (135, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (136, 'Scarf', 'Official club scarf merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (137, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (138, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (139, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (140, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (141, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (142, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (143, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (144, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (145, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (146, 'Cushion', 'Official club cushion merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (147, 'Cushion', 'Official club cushion merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (148, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (149, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (150, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (151, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (152, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (153, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (154, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (155, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (156, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (157, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (158, 'Scarf', 'Official club scarf merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (159, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (160, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (161, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (162, 'Scarf', 'Official club scarf merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (163, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (164, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (165, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (166, 'Pin Badge', 'Official club collectible pin', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (167, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (168, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (169, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (170, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (171, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (172, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (173, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (174, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (175, 'Wristband', 'Official club athletic wristband', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (176, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (177, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (178, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (179, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (180, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (181, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (182, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (183, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (184, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (185, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (186, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (187, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (188, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (189, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (190, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (191, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (192, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (193, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (194, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (195, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (196, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (197, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (198, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (199, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (200, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (201, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (202, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (203, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (204, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (205, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (206, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (207, 'Pin Badge', 'Official club collectible pin', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (208, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (209, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (210, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (211, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (212, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (213, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (214, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (215, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (216, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (217, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (218, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (219, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (220, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (221, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (222, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (223, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (224, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (225, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (226, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (227, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (228, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (229, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (230, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (231, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (232, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (233, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (234, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (235, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (236, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (237, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (238, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (239, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (240, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (241, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (242, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (243, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (244, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (245, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (246, 'Pin Badge', 'Official club collectible pin', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (247, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (248, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (249, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (250, 'Wristband', 'Official club athletic wristband', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (251, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (252, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (253, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (254, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (255, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (256, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (257, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (258, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (259, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (260, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (261, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (262, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (263, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (264, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (265, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (266, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (267, 'Tote Bag', 'Official club tote bag merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (268, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (269, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (270, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (271, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (272, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (273, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (274, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (275, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (276, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (277, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (278, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (279, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (280, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (281, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (282, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (283, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (284, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (285, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (286, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (287, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (288, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (289, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (290, 'Key Ring', 'Official club key ring merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (291, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (292, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (293, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (294, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (295, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (296, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (297, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (298, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (299, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (300, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (301, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (302, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (303, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (304, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (305, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (306, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (307, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (308, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (309, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (310, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (311, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (312, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (313, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (314, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (315, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (316, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (317, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (318, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (319, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (320, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (321, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (322, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (323, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (324, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (325, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (326, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (327, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (328, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (329, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (330, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (331, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (332, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (333, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (334, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (335, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (336, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (337, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (338, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (339, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (340, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (341, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (342, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (343, 'Tote Bag', 'Official club tote bag merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (344, 'Tote Bag', 'Official club tote bag merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (345, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (346, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (347, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (348, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (349, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (350, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (351, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (352, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (353, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (354, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (355, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (356, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (357, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (358, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (359, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (360, 'Scarf', 'Official club scarf merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (361, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (362, 'Wristband', 'Official club athletic wristband', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (363, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (364, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (365, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (366, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (367, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (368, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (369, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (370, 'Wristband', 'Official club athletic wristband', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (371, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (372, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (373, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (374, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (375, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (376, 'Pin Badge', 'Official club collectible pin', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (377, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (378, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (379, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (380, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (381, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (382, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (383, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (384, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (385, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (386, 'Wristband', 'Official club athletic wristband', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (387, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (388, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (389, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (390, 'Pin Badge', 'Official club collectible pin', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (391, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (392, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (393, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (394, 'Tote Bag', 'Official club tote bag merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (395, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (396, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (397, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (398, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (399, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (400, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (401, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (402, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (403, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (404, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (405, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (406, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (407, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (408, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (409, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (410, 'Wristband', 'Official club athletic wristband', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (411, 'Wristband', 'Official club athletic wristband', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (412, 'Pennant', 'Official club pennant merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (413, 'Wristband', 'Official club athletic wristband', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (414, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (415, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (416, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (417, 'Pin Badge', 'Official club collectible pin', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (418, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (419, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (420, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (421, 'Water Bottle', 'Official club hydration merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (422, 'Tote Bag', 'Official club tote bag merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (423, 'Water Bottle', 'Official club hydration merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (424, 'Scarf', 'Official club scarf merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (425, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (426, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (427, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (428, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (429, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (430, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (431, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (432, 'Tote Bag', 'Official club tote bag merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (433, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (434, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (435, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (436, 'Water Bottle', 'Official club hydration merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (437, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (438, 'Key Ring', 'Official club key ring merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (439, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (440, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (441, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (442, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (443, 'Scarf', 'Official club scarf merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (444, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (445, 'Pennant', 'Official club pennant merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (446, 'Pin Badge', 'Official club collectible pin', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (447, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (448, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (449, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (450, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (451, 'Pin Badge', 'Official club collectible pin', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (452, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (453, 'Tote Bag', 'Official club tote bag merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (454, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (455, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (456, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (457, 'Pennant', 'Official club pennant merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (458, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (459, 'Scarf', 'Official club scarf merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (460, 'Cushion', 'Official club cushion merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (461, 'Key Ring', 'Official club key ring merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (462, 'Tote Bag', 'Official club tote bag merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (463, 'Water Bottle', 'Official club hydration merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (464, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (465, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (466, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (467, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (468, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (469, 'Water Bottle', 'Official club hydration merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (470, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (471, 'Pennant', 'Official club pennant merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (472, 'Cushion', 'Official club cushion merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (473, 'Key Ring', 'Official club key ring merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (474, 'Key Ring', 'Official club key ring merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (475, 'Cushion', 'Official club cushion merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (476, 'Cushion', 'Official club cushion merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (477, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (478, 'Wristband', 'Official club athletic wristband', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (479, 'Key Ring', 'Official club key ring merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (480, 'Wristband', 'Official club athletic wristband', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (481, 'Water Bottle', 'Official club hydration merchandise', 'Standard');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (482, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (483, 'Cushion', 'Official club cushion merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (484, 'Water Bottle', 'Official club hydration merchandise', 'Small');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (485, 'Tote Bag', 'Official club tote bag merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (486, 'Scarf', 'Official club scarf merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (487, 'Key Ring', 'Official club key ring merchandise', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (488, 'Wristband', 'Official club athletic wristband', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (489, 'Tote Bag', 'Official club tote bag merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (490, 'Pennant', 'Official club pennant merchandise', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (491, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (492, 'Pennant', 'Official club pennant merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (493, 'Pennant', 'Official club pennant merchandise', 'One Size');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (494, 'Wristband', 'Official club athletic wristband', 'Large');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (495, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (496, 'Pin Badge', 'Official club collectible pin', 'M/L');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (497, 'Cushion', 'Official club cushion merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (498, 'Scarf', 'Official club scarf merchandise', 'S/M');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (499, 'Scarf', 'Official club scarf merchandise', '12 inch');
INSERT INTO Accessories (product_id, accy_type, accy_descript, accy_size) VALUES (500, 'Tote Bag', 'Official club tote bag merchandise', 'Small');
