INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Bayern Munich Wristband Set', 202.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Puma Copa Pure', 243.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Umbro Shin Guards', 246.99, 'Umbro', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Nike Copa Pure', 212.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Copa Pure', 242.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Puma Training Ball', 143.99, 'Puma', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Mizuno Future 7 AG', 145.99, 'Mizuno', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Puma Copa Pure', 241.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Real Madrid Mini Pennant', 225.99, 'Nike', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Chelsea Wristband Set', 148.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Barcelona Away Jersey 2024/25', 224.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'New Balance Future 7 FG', 233.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'New Balance Captain's Armband', 248.99, 'New Balance', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Chelsea Home Jersey 2016/17', 109.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Barcelona Third Jersey 2022/23', 190.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Adidas Captain's Armband', 160.99, 'Adidas', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Umbro Captain's Armband', 233.99, 'Umbro', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Puma Speedportal.1', 221.99, 'Puma', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Puma Speedportal.1', 172.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Puma Captain's Armband', 111.99, 'Puma', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Chelsea Key Ring', 150.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Barcelona Wristband Set', 97.99, 'Puma', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Mizuno Future 7 FG', 85.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Training Ball', 92.99, 'Mizuno', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Real Madrid Wristband Set', 224.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Captain's Armband', 167.99, 'Adidas', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Manchester United Pin Badge Set', 207.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Captain's Armband', 99.99, 'Nike', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Arsenal Mini Pennant', 51.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Umbro Captain's Armband', 87.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Real Madrid Retro Jersey 2022/23', 81.99, 'Mizuno', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'PSG Wristband Set', 245.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Mizuno Copa Pure', 163.99, 'Mizuno', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Training Ball', 150.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Adidas Shin Guards', 193.99, 'Adidas', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Authentic XI Future 7 FG', 50.99, 'Authentic XI', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'LA Galaxy Wristband Set', 39.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Mizuno Shin Guards', 22.99, 'Mizuno', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Manchester United Home Jersey 2021/22', 153.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Umbro Shin Guards', 172.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Manchester United Club Scarf', 201.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Man City Key Ring', 123.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Puma Copa Pure', 66.99, 'Puma', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Bayern Munich Club Scarf', 206.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Training Ball', 136.99, 'Adidas', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Arsenal Third Jersey 2016/17', 104.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Inter Miami Third Jersey 2019/20', 135.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Captain's Armband', 65.99, 'Nike', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Nike Copa Pure', 82.99, 'Nike', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'New Balance Training Ball', 182.99, 'New Balance', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Training Ball', 189.99, 'Umbro', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Puma Future 7 FG', 224.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Speedportal.1', 195.99, 'Umbro', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'PSG Wristband Set', 193.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'LA Galaxy Home Jersey 2019/20', 34.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Puma Phantom GX 2 FG', 224.99, 'Puma', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Nike Training Ball', 87.99, 'Nike', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Barcelona Water Bottle', 235.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Arsenal Pin Badge Set', 113.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Chelsea Club Scarf', 246.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Puma Copa Pure', 52.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Real Madrid Retro Jersey 2022/23', 174.99, 'New Balance', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'New Balance Phantom GX 2 FG', 20.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Puma Captain's Armband', 89.99, 'Puma', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'LA Galaxy Third Jersey 2022/23', 136.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Authentic XI Training Ball', 118.99, 'Authentic XI', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'New Balance Shin Guards', 21.99, 'New Balance', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Puma Training Ball', 148.99, 'Puma', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Manchester United Mini Pennant', 248.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Real Madrid Wristband Set', 129.99, 'Authentic XI', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Man City Home Jersey 2023/24', 89.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Captain's Armband', 157.99, 'Adidas', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Mizuno Captain's Armband', 182.99, 'Mizuno', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Retro Jersey 2021/22', 24.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Mizuno Phantom GX 2 FG', 60.99, 'Mizuno', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Chelsea Water Bottle', 85.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Umbro Captain's Armband', 59.99, 'Umbro', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Puma Future 7 AG', 147.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Real Madrid Third Jersey 2021/22', 199.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Real Madrid Mini Pennant', 244.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Manchester United Mini Pennant', 218.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Adidas Future 7 FG', 122.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Puma Future 7 AG', 196.99, 'Puma', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Inter Miami Wristband Set', 175.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Mizuno Shin Guards', 207.99, 'Mizuno', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Adidas Shin Guards', 75.99, 'Adidas', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Bayern Munich Key Ring', 89.99, 'Mizuno', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Nike Training Ball', 213.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Authentic XI Future 7 FG', 112.99, 'Authentic XI', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Inter Miami Water Bottle', 71.99, 'Umbro', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Mizuno Shin Guards', 38.99, 'Mizuno', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Umbro Copa Pure', 100.99, 'Umbro', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Juventus Club Scarf', 113.99, 'Puma', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'New Balance Copa Pure', 12.99, 'New Balance', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Mini Pennant', 157.99, 'Umbro', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Adidas Speedportal.1', 65.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Nike Phantom GX 2 FG', 166.99, 'Nike', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Arsenal Away Jersey 2016/17', 104.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Authentic XI Future 7 AG', 65.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Mizuno Phantom GX 2 FG', 33.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'LA Galaxy Key Ring', 85.99, 'Authentic XI', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Manchester United Wristband Set', 129.99, 'Adidas', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'New Balance Training Ball', 237.99, 'New Balance', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Liverpool Away Jersey 2013/14', 214.99, 'Authentic XI', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Copa Pure', 28.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Puma Training Ball', 170.99, 'Puma', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Water Bottle', 17.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Real Madrid Away Jersey 2019/20', 244.99, 'Umbro', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Adidas Training Ball', 228.99, 'Adidas', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Juventus Home Jersey 2019/20', 150.99, 'Puma', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Puma Speedportal.1', 98.99, 'Puma', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Key Ring', 57.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Puma Shin Guards', 117.99, 'Puma', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Chelsea Mini Pennant', 163.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Adidas Captain's Armband', 88.99, 'Adidas', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Umbro Speedportal.1', 90.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Nike Copa Pure', 97.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Nike Captain's Armband', 213.99, 'Nike', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Adidas Copa Pure', 249.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'LA Galaxy Wristband Set', 177.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Chelsea Water Bottle', 15.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Phantom GX 2 FG', 17.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Manchester United Wristband Set', 211.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Bayern Munich Retro Jersey 2023/24', 27.99, 'Mizuno', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Puma Shin Guards', 11.99, 'Puma', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Barcelona Mini Pennant', 18.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Juventus Key Ring', 195.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Arsenal Mini Pennant', 244.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Mizuno Training Ball', 158.99, 'Mizuno', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Arsenal Key Ring', 249.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Liverpool Wristband Set', 38.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Man City Away Jersey 2023/24', 101.99, 'Mizuno', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Authentic XI Training Ball', 50.99, 'Authentic XI', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Bayern Munich Retro Jersey 2013/14', 240.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Third Jersey 2021/22', 39.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Inter Miami Key Ring', 29.99, 'Adidas', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Umbro Speedportal.1', 174.99, 'Umbro', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Liverpool Retro Jersey 2024/25', 240.99, 'New Balance', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'LA Galaxy Water Bottle', 209.99, 'Authentic XI', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Puma Captain's Armband', 53.99, 'Puma', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Mizuno Future 7 FG', 148.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Authentic XI Future 7 AG', 159.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Umbro Captain's Armband', 43.99, 'Umbro', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'New Balance Captain's Armband', 140.99, 'New Balance', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Speedportal.1', 67.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Nike Speedportal.1', 190.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Captain's Armband', 219.99, 'Adidas', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Nike Phantom GX 2 FG', 117.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Authentic XI Training Ball', 226.99, 'Authentic XI', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Barcelona Wristband Set', 11.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Captain's Armband', 72.99, 'Umbro', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Juventus Away Jersey 2021/22', 14.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Chelsea Retro Jersey 2019/20', 165.99, 'New Balance', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Barcelona Away Jersey 2016/17', 125.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Bayern Munich Retro Jersey 2024/25', 242.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'LA Galaxy Pin Badge Set', 215.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Umbro Shin Guards', 177.99, 'Umbro', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Authentic XI Future 7 FG', 223.99, 'Authentic XI', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Mizuno Future 7 AG', 187.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Liverpool Retro Jersey 2024/25', 165.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'PSG Retro Jersey 2023/24', 228.99, 'Umbro', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Adidas Captain's Armband', 106.99, 'Adidas', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Juventus Water Bottle', 56.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Chelsea Pin Badge Set', 68.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Manchester United Water Bottle', 174.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Puma Shin Guards', 169.99, 'Puma', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Mizuno Future 7 AG', 220.99, 'Mizuno', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Barcelona Home Jersey 2019/20', 132.99, 'Puma', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'PSG Retro Jersey 2022/23', 48.99, 'Umbro', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Nike Speedportal.1', 142.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Chelsea Third Jersey 2024/25', 203.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Barcelona Water Bottle', 124.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Umbro Speedportal.1', 158.99, 'Umbro', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Third Jersey 2023/24', 231.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'LA Galaxy Water Bottle', 128.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Club Scarf', 132.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Bayern Munich Club Scarf', 49.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Arsenal Key Ring', 26.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Mizuno Captain's Armband', 191.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Man City Retro Jersey 2019/20', 83.99, 'Puma', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'New Balance Phantom GX 2 FG', 201.99, 'New Balance', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Arsenal Third Jersey 2019/20', 210.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Manchester United Pin Badge Set', 52.99, 'Adidas', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Puma Captain's Armband', 30.99, 'Puma', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'LA Galaxy Mini Pennant', 86.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Manchester United Away Jersey 2024/25', 144.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Manchester United Away Jersey 2021/22', 98.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Liverpool Home Jersey 2021/22', 192.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Adidas Speedportal.1', 79.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Nike Training Ball', 188.99, 'Nike', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Manchester United Mini Pennant', 68.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Umbro Captain's Armband', 65.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Manchester United Home Jersey 2023/24', 22.99, 'Umbro', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Authentic XI Training Ball', 40.99, 'Authentic XI', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Barcelona Away Jersey 2013/14', 169.99, 'Mizuno', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Manchester United Pin Badge Set', 104.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'LA Galaxy Club Scarf', 144.99, 'Authentic XI', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Juventus Wristband Set', 170.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Inter Miami Water Bottle', 154.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Real Madrid Retro Jersey 2016/17', 144.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Arsenal Home Jersey 2016/17', 70.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Future 7 FG', 172.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Manchester United Key Ring', 172.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Nike Phantom GX 2 FG', 239.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'New Balance Copa Pure', 162.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'New Balance Speedportal.1', 153.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Mini Pennant', 123.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'PSG Third Jersey 2022/23', 176.99, 'Mizuno', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Juventus Home Jersey 2024/25', 248.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Liverpool Mini Pennant', 72.99, 'Mizuno', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Adidas Future 7 AG', 83.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Shin Guards', 226.99, 'Adidas', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Juventus Third Jersey 2019/20', 51.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'New Balance Training Ball', 146.99, 'New Balance', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'New Balance Phantom GX 2 FG', 165.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Chelsea Key Ring', 11.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Real Madrid Away Jersey 2024/25', 138.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Speedportal.1', 122.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Authentic XI Speedportal.1', 62.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Juventus Club Scarf', 200.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Man City Pin Badge Set', 185.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Juventus Home Jersey 2023/24', 53.99, 'Adidas', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'LA Galaxy Home Jersey 2024/25', 13.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Umbro Shin Guards', 96.99, 'Umbro', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Authentic XI Captain's Armband', 112.99, 'Authentic XI', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Puma Training Ball', 23.99, 'Puma', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Speedportal.1', 36.99, 'Puma', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'New Balance Captain's Armband', 231.99, 'New Balance', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Captain's Armband', 109.99, 'Puma', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Bayern Munich Third Jersey 2021/22', 25.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Arsenal Key Ring', 109.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Umbro Future 7 AG', 210.99, 'Umbro', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Man City Away Jersey 2024/25', 71.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'LA Galaxy Away Jersey 2024/25', 161.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Nike Shin Guards', 206.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Authentic XI Training Ball', 236.99, 'Authentic XI', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Real Madrid Water Bottle', 187.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'New Balance Phantom GX 2 FG', 53.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Mizuno Copa Pure', 25.99, 'Mizuno', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Inter Miami Away Jersey 2022/23', 32.99, 'Authentic XI', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Umbro Copa Pure', 188.99, 'Umbro', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Umbro Training Ball', 206.99, 'Umbro', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'New Balance Shin Guards', 164.99, 'New Balance', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'New Balance Shin Guards', 150.99, 'New Balance', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Arsenal Key Ring', 100.99, 'New Balance', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Captain's Armband', 171.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Bayern Munich Club Scarf', 232.99, 'Adidas', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Chelsea Third Jersey 2024/25', 172.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'LA Galaxy Club Scarf', 162.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Juventus Mini Pennant', 139.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Nike Shin Guards', 127.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Juventus Wristband Set', 27.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Real Madrid Home Jersey 2024/25', 234.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'New Balance Captain's Armband', 54.99, 'New Balance', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Liverpool Retro Jersey 2023/24', 155.99, 'Adidas', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Juventus Retro Jersey 2024/25', 158.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Arsenal Away Jersey 2016/17', 117.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Nike Copa Pure', 21.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Nike Copa Pure', 213.99, 'Nike', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Adidas Speedportal.1', 176.99, 'Adidas', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Nike Future 7 FG', 155.99, 'Nike', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Puma Speedportal.1', 154.99, 'Puma', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Bayern Munich Key Ring', 29.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Authentic XI Shin Guards', 42.99, 'Authentic XI', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Adidas Shin Guards', 122.99, 'Adidas', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Home Jersey 2013/14', 223.99, 'Umbro', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Arsenal Away Jersey 2021/22', 35.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'LA Galaxy Third Jersey 2024/25', 215.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Real Madrid Third Jersey 2019/20', 14.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Bayern Munich Key Ring', 248.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Home Jersey 2021/22', 75.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Away Jersey 2023/24', 62.99, 'Umbro', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Arsenal Key Ring', 143.99, 'Puma', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Juventus Home Jersey 2021/22', 192.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Juventus Home Jersey 2021/22', 167.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Adidas Future 7 AG', 95.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'New Balance Captain's Armband', 240.99, 'New Balance', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Pin Badge Set', 119.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Copa Pure', 19.99, 'Mizuno', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Inter Miami Pin Badge Set', 82.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Captain's Armband', 173.99, 'Puma', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Nike Future 7 AG', 54.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Training Ball', 207.99, 'Puma', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Authentic XI Future 7 FG', 124.99, 'Authentic XI', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Liverpool Home Jersey 2023/24', 178.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Authentic XI Captain's Armband', 76.99, 'Authentic XI', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Future 7 FG', 25.99, 'Mizuno', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Inter Miami Away Jersey 2022/23', 127.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Bayern Munich Water Bottle', 118.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Mizuno Captain's Armband', 36.99, 'Mizuno', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'LA Galaxy Away Jersey 2016/17', 140.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Puma Shin Guards', 154.99, 'Puma', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Real Madrid Away Jersey 2016/17', 198.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Puma Training Ball', 122.99, 'Puma', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Bayern Munich Away Jersey 2024/25', 216.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Puma Shin Guards', 140.99, 'Puma', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Authentic XI Shin Guards', 11.99, 'Authentic XI', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Bayern Munich Mini Pennant', 235.99, 'Adidas', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Authentic XI Training Ball', 90.99, 'Authentic XI', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Barcelona Water Bottle', 222.99, 'Umbro', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Home Jersey 2021/22', 27.99, 'Mizuno', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Manchester United Club Scarf', 41.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Authentic XI Phantom GX 2 FG', 79.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Arsenal Mini Pennant', 214.99, 'Mizuno', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Authentic XI Training Ball', 193.99, 'Authentic XI', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Authentic XI Speedportal.1', 91.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Barcelona Club Scarf', 171.99, 'Puma', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Arsenal Third Jersey 2022/23', 113.99, 'Umbro', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Puma Training Ball', 36.99, 'Puma', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'PSG Retro Jersey 2019/20', 155.99, 'Umbro', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Umbro Training Ball', 207.99, 'Umbro', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Puma Captain's Armband', 151.99, 'Puma', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Nike Captain's Armband', 190.99, 'Nike', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Nike Shin Guards', 35.99, 'Nike', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Man City Home Jersey 2019/20', 216.99, 'Puma', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Arsenal Third Jersey 2023/24', 174.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Nike Shin Guards', 191.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Authentic XI Speedportal.1', 194.99, 'Authentic XI', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'LA Galaxy Retro Jersey 2022/23', 171.99, 'Mizuno', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Mizuno Shin Guards', 215.99, 'Mizuno', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Arsenal Retro Jersey 2016/17', 248.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Authentic XI Shin Guards', 237.99, 'Authentic XI', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Puma Speedportal.1', 183.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Man City Home Jersey 2021/22', 23.99, 'Nike', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'LA Galaxy Water Bottle', 63.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Nike Shin Guards', 139.99, 'Nike', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Liverpool Club Scarf', 98.99, 'Umbro', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'LA Galaxy Home Jersey 2023/24', 136.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Inter Miami Third Jersey 2022/23', 115.99, 'New Balance', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'PSG Key Ring', 17.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'PSG Home Jersey 2019/20', 211.99, 'New Balance', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Nike Shin Guards', 235.99, 'Nike', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Mizuno Phantom GX 2 FG', 12.99, 'Mizuno', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'New Balance Copa Pure', 46.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Home Jersey 2021/22', 86.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Bayern Munich Third Jersey 2021/22', 161.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Puma Speedportal.1', 113.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'PSG Home Jersey 2023/24', 78.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Real Madrid Club Scarf', 138.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Authentic XI Captain's Armband', 242.99, 'Authentic XI', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Inter Miami Away Jersey 2024/25', 154.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Mizuno Future 7 FG', 239.99, 'Mizuno', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Inter Miami Wristband Set', 56.99, 'Adidas', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Mizuno Speedportal.1', 71.99, 'Mizuno', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'New Balance Speedportal.1', 49.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Adidas Training Ball', 158.99, 'Adidas', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Mizuno Captain's Armband', 145.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Mini Pennant', 39.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'New Balance Future 7 AG', 115.99, 'New Balance', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Authentic XI Phantom GX 2 FG', 146.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Nike Future 7 FG', 89.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Arsenal Third Jersey 2023/24', 136.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Manchester United Mini Pennant', 212.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Bayern Munich Away Jersey 2023/24', 72.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Umbro Captain's Armband', 12.99, 'Umbro', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Copa Pure', 86.99, 'Umbro', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Shin Guards', 46.99, 'Umbro', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Authentic XI Phantom GX 2 FG', 129.99, 'Authentic XI', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Speedportal.1', 51.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'PSG Away Jersey 2021/22', 28.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Liverpool Away Jersey 2024/25', 95.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Nike Copa Pure', 75.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Barcelona Away Jersey 2013/14', 167.99, 'New Balance', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'PSG Wristband Set', 153.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Umbro Captain's Armband', 43.99, 'Umbro', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Nike Future 7 AG', 37.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Mizuno Shin Guards', 109.99, 'Mizuno', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Captain's Armband', 45.99, 'Nike', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Mizuno Captain's Armband', 204.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Pin Badge Set', 113.99, 'Nike', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Shin Guards', 158.99, 'Adidas', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Liverpool Club Scarf', 179.99, 'Umbro', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Puma Training Ball', 97.99, 'Puma', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Manchester United Retro Jersey 2021/22', 123.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Training Ball', 161.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'LA Galaxy Away Jersey 2013/14', 61.99, 'Adidas', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Nike Speedportal.1', 27.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Copa Pure', 176.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'New Balance Copa Pure', 203.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Authentic XI Shin Guards', 218.99, 'Authentic XI', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Man City Wristband Set', 237.99, 'Puma', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Nike Copa Pure', 11.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Chelsea Club Scarf', 133.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Key Ring', 224.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Authentic XI Copa Pure', 39.99, 'Authentic XI', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Man City Third Jersey 2024/25', 222.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Juventus Water Bottle', 246.99, 'Mizuno', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Nike Shin Guards', 178.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Umbro Training Ball', 47.99, 'Umbro', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Bayern Munich Retro Jersey 2024/25', 21.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'LA Galaxy Pin Badge Set', 105.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Liverpool Mini Pennant', 25.99, 'Nike', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Arsenal Home Jersey 2022/23', 52.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Adidas Speedportal.1', 99.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Puma Shin Guards', 245.99, 'Puma', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Puma Copa Pure', 245.99, 'Puma', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Umbro Shin Guards', 202.99, 'Umbro', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'LA Galaxy Home Jersey 2016/17', 113.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Umbro Phantom GX 2 FG', 193.99, 'Umbro', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Juventus Third Jersey 2021/22', 75.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Authentic XI Future 7 FG', 207.99, 'Authentic XI', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Arsenal Away Jersey 2013/14', 105.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Liverpool Key Ring', 182.99, 'Umbro', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Adidas Future 7 FG', 161.99, 'Adidas', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Authentic XI Copa Pure', 114.99, 'Authentic XI', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Authentic XI Captain's Armband', 190.99, 'Authentic XI', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'New Balance Copa Pure', 32.99, 'New Balance', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Arsenal Key Ring', 33.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Inter Miami Club Scarf', 65.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Manchester United Home Jersey 2022/23', 19.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'PSG Away Jersey 2024/25', 98.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'New Balance Copa Pure', 160.99, 'New Balance', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Future 7 FG', 36.99, 'Mizuno', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Liverpool Away Jersey 2023/24', 227.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Adidas Phantom GX 2 FG', 178.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Chelsea Home Jersey 2023/24', 236.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Man City Pin Badge Set', 245.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Future 7 FG', 170.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Manchester United Third Jersey 2023/24', 23.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Adidas Shin Guards', 106.99, 'Adidas', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Nike Captain's Armband', 145.99, 'Nike', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Captain's Armband', 213.99, 'Umbro', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Future 7 FG', 136.99, 'Mizuno', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Juventus Pin Badge Set', 154.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'LA Galaxy Away Jersey 2019/20', 163.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Arsenal Water Bottle', 32.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Barcelona Retro Jersey 2016/17', 59.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Juventus Club Scarf', 131.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Mizuno Training Ball', 206.99, 'Mizuno', '2021/22', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Mizuno Future 7 AG', 23.99, 'Mizuno', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Umbro Phantom GX 2 FG', 226.99, 'Umbro', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Speedportal.1', 145.99, 'Umbro', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Mizuno Training Ball', 191.99, 'Mizuno', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Copa Pure', 40.99, 'Adidas', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'New Balance Captain's Armband', 167.99, 'New Balance', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'PSG Home Jersey 2021/22', 164.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Arsenal Third Jersey 2016/17', 140.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'PSG Home Jersey 2021/22', 232.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Liverpool Retro Jersey 2024/25', 51.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'New Balance Speedportal.1', 13.99, 'New Balance', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Real Madrid Home Jersey 2022/23', 106.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'LA Galaxy Retro Jersey 2023/24', 97.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Retro Jersey 2022/23', 65.99, 'Authentic XI', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'New Balance Shin Guards', 148.99, 'New Balance', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'PSG Third Jersey 2021/22', 205.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Real Madrid Home Jersey 2024/25', 16.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Nike Shin Guards', 188.99, 'Nike', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Chelsea Third Jersey 2022/23', 96.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Mizuno Training Ball', 119.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Arsenal Home Jersey 2013/14', 224.99, 'Mizuno', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Juventus Pin Badge Set', 172.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Nike Copa Pure', 215.99, 'Nike', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Umbro Future 7 FG', 203.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Training Ball', 71.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Umbro Speedportal.1', 137.99, 'Umbro', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Real Madrid Retro Jersey 2013/14', 63.99, 'Authentic XI', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Man City Home Jersey 2019/20', 175.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Authentic XI Captain's Armband', 45.99, 'Authentic XI', '2024/25', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Authentic XI Future 7 FG', 126.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Liverpool Wristband Set', 128.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Mizuno Training Ball', 184.99, 'Mizuno', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Captain's Armband', 17.99, 'Adidas', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Mizuno Speedportal.1', 93.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Mizuno Training Ball', 166.99, 'Mizuno', '2019/20', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Nike Speedportal.1', 200.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Adidas Shin Guards', 49.99, 'Adidas', '2023/24', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Authentic XI Captain's Armband', 204.99, 'Authentic XI', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Mizuno Training Ball', 94.99, 'Mizuno', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Umbro Captain's Armband', 204.99, 'Umbro', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Liverpool Water Bottle', 108.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Arsenal Mini Pennant', 130.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Inter Miami Home Jersey 2024/25', 107.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Nike Phantom GX 2 FG', 41.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Man City Third Jersey 2022/23', 10.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Umbro Training Ball', 166.99, 'Umbro', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Liverpool Third Jersey 2022/23', 96.99, 'Mizuno', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Chelsea Wristband Set', 61.99, 'Authentic XI', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Bayern Munich Away Jersey 2019/20', 211.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Umbro Captain's Armband', 193.99, 'Umbro', '2022/23', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Inter Miami Mini Pennant', 236.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Puma Phantom GX 2 FG', 237.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Barcelona Wristband Set', 97.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'PSG Mini Pennant', 209.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Chelsea Retro Jersey 2021/22', 123.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Puma Shin Guards', 216.99, 'Puma', '2016/17', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Nike Shin Guards', 190.99, 'Nike', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Umbro Phantom GX 2 FG', 241.99, 'Umbro', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'PSG Away Jersey 2019/20', 136.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Man City Mini Pennant', 174.99, 'Adidas', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Water Bottle', 167.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Home Jersey 2013/14', 138.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'New Balance Phantom GX 2 FG', 56.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Pin Badge Set', 52.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Arsenal Retro Jersey 2019/20', 91.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Chelsea Water Bottle', 236.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Authentic XI Speedportal.1', 73.99, 'Authentic XI', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Puma Captain's Armband', 15.99, 'Puma', '2013/14', 'Equipment');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Puma Phantom GX 2 FG', 123.99, 'Puma', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Real Madrid Home Jersey 2019/20', 181.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Bayern Munich Wristband Set', 11.99, 'Puma', '2021/22', 'Accessories');