INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'New Balance Phantom GX 2 FG', 164.99, 'New Balance', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'PSG Captain's Armband', 248.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Manchester United Key Ring', 49.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Arsenal Shin Guards', 103.99, 'Authentic XI', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Real Madrid Third Jersey 2022/23', 38.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Juventus Mini Pennant', 38.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Umbro Future 7 AG', 150.99, 'Umbro', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Future 7 AG', 106.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Water Bottle', 183.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Adidas Future 7 FG', 116.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'PSG Pin Badge Set', 245.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'New Balance Speedportal.1', 244.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Man City Pin Badge Set', 40.99, 'Umbro', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'PSG Home Jersey 2013/14', 75.99, 'Authentic XI', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Nike Copa Pure', 89.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Umbro Future 7 AG', 89.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Inter Miami Water Bottle', 206.99, 'Umbro', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Adidas Future 7 FG', 95.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Authentic XI Speedportal.1', 146.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Man City Away Jersey 2023/24', 38.99, 'Mizuno', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Chelsea Club Scarf', 47.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'New Balance Phantom GX 2 FG', 57.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Arsenal Away Jersey 2013/14', 133.99, 'New Balance', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'New Balance Phantom GX 2 FG', 71.99, 'New Balance', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Nike Future 7 AG', 81.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Man City Training Ball', 83.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Away Jersey 2013/14', 201.99, 'Mizuno', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'PSG Mini Pennant', 42.99, 'Nike', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Captain's Armband', 180.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Juventus Training Ball', 31.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Bayern Munich Captain's Armband', 188.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Retro Jersey 2019/20', 92.99, 'Mizuno', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Future 7 AG', 86.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'PSG Pin Badge Set', 195.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Man City Home Jersey 2024/25', 101.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Chelsea Home Jersey 2022/23', 107.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Chelsea Retro Jersey 2016/17', 45.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Manchester United Retro Jersey 2024/25', 219.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'New Balance Future 7 FG', 15.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Man City Key Ring', 207.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'New Balance Copa Pure', 28.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Adidas Copa Pure', 63.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Barcelona Shin Guards', 148.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Liverpool Mini Pennant', 157.99, 'Authentic XI', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Juventus Retro Jersey 2013/14', 23.99, 'Mizuno', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Nike Future 7 FG', 189.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Juventus Club Scarf', 71.99, 'New Balance', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'PSG Mini Pennant', 72.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'New Balance Speedportal.1', 211.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Real Madrid Training Ball', 43.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Liverpool Home Jersey 2021/22', 151.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Liverpool Retro Jersey 2021/22', 56.99, 'Nike', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Chelsea Wristband Set', 77.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Barcelona Key Ring', 189.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Chelsea Third Jersey 2021/22', 163.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Barcelona Away Jersey 2023/24', 19.99, 'Umbro', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Man City Training Ball', 128.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'PSG Retro Jersey 2019/20', 206.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Umbro Speedportal.1', 88.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Real Madrid Water Bottle', 233.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Arsenal Key Ring', 216.99, 'Authentic XI', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Authentic XI Copa Pure', 228.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'PSG Retro Jersey 2019/20', 31.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Liverpool Pin Badge Set', 215.99, 'Umbro', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Liverpool Home Jersey 2021/22', 162.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Liverpool Mini Pennant', 68.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Future 7 AG', 135.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Future 7 AG', 192.99, 'Umbro', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Umbro Future 7 AG', 137.99, 'Umbro', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Adidas Copa Pure', 69.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'PSG Captain's Armband', 166.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Arsenal Home Jersey 2023/24', 168.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Mizuno Future 7 FG', 118.99, 'Mizuno', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'LA Galaxy Wristband Set', 235.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Liverpool Training Ball', 220.99, 'Umbro', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Liverpool Club Scarf', 234.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'New Balance Future 7 FG', 84.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Inter Miami Away Jersey 2023/24', 85.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Arsenal Third Jersey 2021/22', 12.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Real Madrid Home Jersey 2013/14', 154.99, 'Adidas', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Phantom GX 2 FG', 45.99, 'Umbro', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'PSG Captain's Armband', 187.99, 'Umbro', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Authentic XI Future 7 AG', 32.99, 'Authentic XI', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Nike Speedportal.1', 133.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'LA Galaxy Retro Jersey 2016/17', 161.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Inter Miami Pin Badge Set', 224.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Puma Future 7 AG', 100.99, 'Puma', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Speedportal.1', 204.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Manchester United Home Jersey 2016/17', 130.99, 'Puma', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'LA Galaxy Shin Guards', 44.99, 'Umbro', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'New Balance Phantom GX 2 FG', 113.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Nike Future 7 AG', 65.99, 'Nike', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'LA Galaxy Pin Badge Set', 226.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Manchester United Water Bottle', 20.99, 'Puma', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Barcelona Shin Guards', 140.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Away Jersey 2019/20', 170.99, 'Umbro', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Liverpool Away Jersey 2016/17', 188.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Manchester United Training Ball', 226.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Barcelona Retro Jersey 2016/17', 145.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Barcelona Third Jersey 2024/25', 29.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Manchester United Home Jersey 2022/23', 51.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Barcelona Third Jersey 2024/25', 242.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Adidas Future 7 FG', 97.99, 'Adidas', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'LA Galaxy Away Jersey 2019/20', 231.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Barcelona Training Ball', 99.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Juventus Club Scarf', 42.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Liverpool Retro Jersey 2019/20', 20.99, 'New Balance', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Liverpool Retro Jersey 2022/23', 164.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Chelsea Away Jersey 2022/23', 22.99, 'New Balance', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'LA Galaxy Retro Jersey 2016/17', 201.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Puma Copa Pure', 127.99, 'Puma', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Real Madrid Training Ball', 60.99, 'Mizuno', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Arsenal Wristband Set', 203.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Mizuno Phantom GX 2 FG', 222.99, 'Mizuno', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Authentic XI Future 7 FG', 201.99, 'Authentic XI', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'LA Galaxy Key Ring', 121.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Liverpool Club Scarf', 58.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Barcelona Training Ball', 11.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Chelsea Away Jersey 2024/25', 216.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Manchester United Pin Badge Set', 177.99, 'Mizuno', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Juventus Training Ball', 104.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'PSG Retro Jersey 2021/22', 146.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Nike Speedportal.1', 195.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'PSG Club Scarf', 43.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'LA Galaxy Training Ball', 197.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Phantom GX 2 FG', 215.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Bayern Munich Home Jersey 2024/25', 220.99, 'New Balance', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Manchester United Shin Guards', 13.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Manchester United Home Jersey 2024/25', 64.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Bayern Munich Wristband Set', 171.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Barcelona Captain's Armband', 177.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Phantom GX 2 FG', 159.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Juventus Home Jersey 2024/25', 242.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Speedportal.1', 185.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Puma Copa Pure', 228.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Barcelona Away Jersey 2021/22', 128.99, 'Nike', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Inter Miami Home Jersey 2024/25', 246.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Man City Home Jersey 2022/23', 126.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Puma Future 7 AG', 190.99, 'Puma', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Barcelona Training Ball', 33.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Liverpool Away Jersey 2024/25', 19.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Juventus Away Jersey 2013/14', 131.99, 'Mizuno', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Liverpool Home Jersey 2016/17', 56.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Manchester United Club Scarf', 190.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Chelsea Away Jersey 2016/17', 130.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Club Scarf', 18.99, 'Umbro', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Chelsea Pin Badge Set', 105.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Adidas Speedportal.1', 56.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Authentic XI Copa Pure', 13.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Phantom GX 2 FG', 112.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'LA Galaxy Home Jersey 2016/17', 157.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Man City Key Ring', 136.99, 'Authentic XI', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Bayern Munich Training Ball', 237.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Arsenal Training Ball', 161.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Mizuno Phantom GX 2 FG', 221.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Chelsea Training Ball', 52.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Umbro Future 7 AG', 201.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Bayern Munich Away Jersey 2021/22', 10.99, 'Nike', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'New Balance Future 7 AG', 126.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'LA Galaxy Home Jersey 2016/17', 186.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Nike Future 7 AG', 165.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Retro Jersey 2021/22', 161.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Adidas Speedportal.1', 17.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Adidas Future 7 AG', 78.99, 'Adidas', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Retro Jersey 2023/24', 54.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Chelsea Away Jersey 2016/17', 112.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Inter Miami Club Scarf', 249.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Juventus Club Scarf', 215.99, 'Puma', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Umbro Copa Pure', 54.99, 'Umbro', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Adidas Copa Pure', 199.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Real Madrid Pin Badge Set', 203.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Umbro Future 7 FG', 248.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Liverpool Away Jersey 2016/17', 97.99, 'Adidas', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Real Madrid Training Ball', 94.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Man City Pin Badge Set', 61.99, 'Umbro', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Chelsea Water Bottle', 26.99, 'Adidas', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Puma Future 7 AG', 69.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Arsenal Third Jersey 2023/24', 211.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Liverpool Key Ring', 47.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Authentic XI Speedportal.1', 152.99, 'Authentic XI', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Mizuno Speedportal.1', 244.99, 'Mizuno', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Man City Wristband Set', 192.99, 'Puma', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Juventus Retro Jersey 2013/14', 226.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Juventus Training Ball', 99.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Future 7 FG', 157.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Real Madrid Retro Jersey 2019/20', 146.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'LA Galaxy Third Jersey 2023/24', 136.99, 'Nike', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Copa Pure', 142.99, 'Mizuno', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Real Madrid Captain's Armband', 187.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Nike Copa Pure', 205.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Inter Miami Training Ball', 79.99, 'Adidas', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Arsenal Home Jersey 2019/20', 10.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Copa Pure', 194.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Chelsea Third Jersey 2016/17', 126.99, 'Puma', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Phantom GX 2 FG', 161.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Barcelona Water Bottle', 118.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Authentic XI Phantom GX 2 FG', 249.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Manchester United Mini Pennant', 43.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Inter Miami Training Ball', 225.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Umbro Phantom GX 2 FG', 88.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Inter Miami Retro Jersey 2021/22', 181.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Liverpool Mini Pennant', 124.99, 'New Balance', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Away Jersey 2022/23', 47.99, 'Mizuno', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Umbro Future 7 FG', 126.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Nike Phantom GX 2 FG', 25.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'New Balance Future 7 FG', 195.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Adidas Future 7 FG', 104.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Arsenal Pin Badge Set', 167.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Chelsea Third Jersey 2022/23', 221.99, 'New Balance', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'New Balance Future 7 FG', 140.99, 'New Balance', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Arsenal Key Ring', 134.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Pin Badge Set', 92.99, 'Adidas', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Authentic XI Future 7 FG', 99.99, 'Authentic XI', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Chelsea Water Bottle', 141.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Manchester United Pin Badge Set', 164.99, 'Mizuno', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Bayern Munich Home Jersey 2024/25', 238.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Nike Copa Pure', 97.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Barcelona Wristband Set', 59.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Man City Away Jersey 2022/23', 105.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Liverpool Home Jersey 2021/22', 108.99, 'Mizuno', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Copa Pure', 40.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Juventus Retro Jersey 2013/14', 130.99, 'Puma', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Man City Retro Jersey 2023/24', 229.99, 'Nike', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Juventus Key Ring', 114.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Barcelona Pin Badge Set', 96.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Liverpool Away Jersey 2016/17', 62.99, 'Puma', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Home Jersey 2021/22', 64.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Bayern Munich Home Jersey 2021/22', 231.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Training Ball', 174.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Manchester United Home Jersey 2024/25', 119.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Man City Key Ring', 68.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Adidas Future 7 AG', 231.99, 'Adidas', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Manchester United Home Jersey 2016/17', 104.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Adidas Future 7 AG', 36.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Mizuno Copa Pure', 89.99, 'Mizuno', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Real Madrid Third Jersey 2022/23', 233.99, 'Umbro', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Retro Jersey 2024/25', 218.99, 'New Balance', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Mizuno Future 7 AG', 50.99, 'Mizuno', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'PSG Mini Pennant', 169.99, 'Nike', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Captain's Armband', 225.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Away Jersey 2021/22', 208.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Mizuno Speedportal.1', 142.99, 'Mizuno', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Arsenal Club Scarf', 215.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Third Jersey 2024/25', 220.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Liverpool Away Jersey 2021/22', 178.99, 'Nike', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Juventus Third Jersey 2024/25', 138.99, 'New Balance', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Inter Miami Key Ring', 91.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Nike Copa Pure', 97.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Authentic XI Phantom GX 2 FG', 94.99, 'Authentic XI', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'PSG Away Jersey 2016/17', 88.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Adidas Copa Pure', 223.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Juventus Third Jersey 2013/14', 79.99, 'Puma', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'LA Galaxy Third Jersey 2023/24', 241.99, 'Puma', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Nike Future 7 AG', 104.99, 'Nike', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Bayern Munich Away Jersey 2021/22', 202.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Real Madrid Retro Jersey 2016/17', 51.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Nike Copa Pure', 114.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Inter Miami Home Jersey 2024/25', 149.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'New Balance Future 7 AG', 116.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Home Jersey 2022/23', 142.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'PSG Pin Badge Set', 125.99, 'Puma', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Chelsea Club Scarf', 89.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Authentic XI Speedportal.1', 241.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Bayern Munich Captain's Armband', 242.99, 'Nike', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Barcelona Pin Badge Set', 18.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Man City Third Jersey 2016/17', 105.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Umbro Future 7 AG', 135.99, 'Umbro', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Barcelona Wristband Set', 118.99, 'Adidas', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Umbro Phantom GX 2 FG', 197.99, 'Umbro', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Authentic XI Future 7 FG', 94.99, 'Authentic XI', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Real Madrid Key Ring', 43.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Arsenal Away Jersey 2021/22', 29.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'LA Galaxy Water Bottle', 111.99, 'Umbro', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Nike Phantom GX 2 FG', 61.99, 'Nike', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Umbro Future 7 AG', 172.99, 'Umbro', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Barcelona Mini Pennant', 121.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Inter Miami Away Jersey 2013/14', 40.99, 'Authentic XI', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Man City Third Jersey 2019/20', 118.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Man City Club Scarf', 199.99, 'Puma', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Real Madrid Pin Badge Set', 16.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Adidas Phantom GX 2 FG', 71.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Adidas Future 7 FG', 24.99, 'Adidas', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Barcelona Away Jersey 2019/20', 241.99, 'Mizuno', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Puma Copa Pure', 227.99, 'Puma', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'New Balance Speedportal.1', 160.99, 'New Balance', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Man City Home Jersey 2013/14', 64.99, 'Adidas', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Real Madrid Shin Guards', 239.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'LA Galaxy Club Scarf', 237.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Training Ball', 243.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Bayern Munich Club Scarf', 12.99, 'Authentic XI', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'PSG Captain's Armband', 225.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'LA Galaxy Third Jersey 2016/17', 148.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Real Madrid Third Jersey 2016/17', 190.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Man City Third Jersey 2024/25', 217.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Barcelona Retro Jersey 2019/20', 220.99, 'New Balance', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Arsenal Captain's Armband', 115.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Inter Miami Mini Pennant', 195.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Puma Future 7 AG', 226.99, 'Puma', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'PSG Away Jersey 2016/17', 48.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Arsenal Key Ring', 30.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Inter Miami Home Jersey 2022/23', 245.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Chelsea Shin Guards', 142.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Authentic XI Phantom GX 2 FG', 236.99, 'Authentic XI', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'New Balance Speedportal.1', 236.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'LA Galaxy Water Bottle', 107.99, 'Nike', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Manchester United Third Jersey 2021/22', 74.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'LA Galaxy Away Jersey 2019/20', 116.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Liverpool Shin Guards', 139.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Adidas Copa Pure', 198.99, 'Adidas', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Umbro Speedportal.1', 116.99, 'Umbro', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Authentic XI Future 7 FG', 208.99, 'Authentic XI', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Wristband Set', 161.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Juventus Third Jersey 2021/22', 161.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Pin Badge Set', 120.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'LA Galaxy Third Jersey 2016/17', 69.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Chelsea Third Jersey 2013/14', 247.99, 'Puma', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Bayern Munich Retro Jersey 2023/24', 135.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Juventus Retro Jersey 2022/23', 224.99, 'Authentic XI', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Barcelona Retro Jersey 2016/17', 190.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Inter Miami Wristband Set', 97.99, 'Mizuno', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Adidas Speedportal.1', 207.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Barcelona Mini Pennant', 198.99, 'Umbro', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Liverpool Training Ball', 245.99, 'Authentic XI', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Umbro Speedportal.1', 93.99, 'Umbro', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'New Balance Copa Pure', 38.99, 'New Balance', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Juventus Home Jersey 2016/17', 194.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'New Balance Future 7 FG', 174.99, 'New Balance', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Nike Copa Pure', 112.99, 'Nike', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Bayern Munich Third Jersey 2022/23', 11.99, 'Authentic XI', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Puma Phantom GX 2 FG', 47.99, 'Puma', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Manchester United Retro Jersey 2016/17', 223.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Pin Badge Set', 106.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Inter Miami Home Jersey 2023/24', 143.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Manchester United Water Bottle', 147.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'LA Galaxy Water Bottle', 193.99, 'Adidas', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Nike Copa Pure', 103.99, 'Nike', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Liverpool Club Scarf', 110.99, 'Adidas', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Man City Home Jersey 2022/23', 231.99, 'Puma', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Barcelona Water Bottle', 103.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Real Madrid Third Jersey 2013/14', 137.99, 'Puma', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Arsenal Wristband Set', 39.99, 'Authentic XI', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'PSG Wristband Set', 129.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'LA Galaxy Captain's Armband', 109.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Puma Speedportal.1', 217.99, 'Puma', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Mizuno Phantom GX 2 FG', 54.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Umbro Phantom GX 2 FG', 177.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Man City Third Jersey 2019/20', 32.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'New Balance Future 7 AG', 249.99, 'New Balance', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Liverpool Third Jersey 2024/25', 13.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Juventus Home Jersey 2013/14', 208.99, 'New Balance', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Umbro Future 7 FG', 141.99, 'Umbro', '2013/14', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Third Jersey 2019/20', 72.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Barcelona Shin Guards', 122.99, 'Mizuno', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'LA Galaxy Away Jersey 2023/24', 116.99, 'Umbro', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'LA Galaxy Mini Pennant', 92.99, 'New Balance', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Liverpool Shin Guards', 163.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'LA Galaxy Home Jersey 2016/17', 158.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Mizuno Future 7 FG', 28.99, 'Mizuno', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Man City Club Scarf', 162.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Real Madrid Water Bottle', 22.99, 'Nike', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Adidas Future 7 AG', 224.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Manchester United Retro Jersey 2021/22', 109.99, 'New Balance', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Manchester United Away Jersey 2022/23', 198.99, 'Adidas', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Inter Miami Mini Pennant', 120.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Man City Pin Badge Set', 73.99, 'Mizuno', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Real Madrid Shin Guards', 167.99, 'Puma', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Liverpool Pin Badge Set', 101.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'PSG Club Scarf', 124.99, 'Umbro', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Arsenal Training Ball', 139.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Pin Badge Set', 206.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'New Balance Copa Pure', 52.99, 'New Balance', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Chelsea Away Jersey 2016/17', 161.99, 'New Balance', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Real Madrid Retro Jersey 2013/14', 86.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Phantom GX 2 FG', 58.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Liverpool Away Jersey 2016/17', 67.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'LA Galaxy Third Jersey 2021/22', 181.99, 'Authentic XI', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'LA Galaxy Pin Badge Set', 159.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Inter Miami Home Jersey 2013/14', 30.99, 'Adidas', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Bayern Munich Third Jersey 2024/25', 249.99, 'Umbro', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Adidas Phantom GX 2 FG', 59.99, 'Adidas', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Nike Future 7 AG', 120.99, 'Nike', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Arsenal Away Jersey 2021/22', 124.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Inter Miami Away Jersey 2019/20', 126.99, 'Puma', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Umbro Phantom GX 2 FG', 183.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Arsenal Water Bottle', 193.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'PSG Away Jersey 2023/24', 203.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Chelsea Wristband Set', 19.99, 'Nike', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Authentic XI Future 7 AG', 237.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Puma Phantom GX 2 FG', 213.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Inter Miami Third Jersey 2019/20', 226.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'Umbro Future 7 FG', 141.99, 'Umbro', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Chelsea Pin Badge Set', 148.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Authentic XI Future 7 FG', 234.99, 'Authentic XI', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Barcelona Home Jersey 2023/24', 216.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'LA Galaxy Retro Jersey 2024/25', 244.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Bayern Munich Retro Jersey 2016/17', 220.99, 'Nike', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (3, 'Juventus Captain's Armband', 77.99, 'Nike', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Authentic XI Speedportal.1', 76.99, 'Authentic XI', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Inter Miami Third Jersey 2023/24', 60.99, 'Nike', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Puma Speedportal.1', 171.99, 'Puma', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Arsenal Wristband Set', 166.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Adidas Future 7 FG', 131.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (16, 'Arsenal Club Scarf', 134.99, 'Umbro', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Chelsea Water Bottle', 127.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Nike Future 7 FG', 176.99, 'Nike', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Adidas Copa Pure', 168.99, 'Adidas', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Manchester United Home Jersey 2024/25', 79.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'LA Galaxy Home Jersey 2019/20', 236.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Authentic XI Future 7 FG', 44.99, 'Authentic XI', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Real Madrid Shin Guards', 131.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Manchester United Training Ball', 129.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Arsenal Club Scarf', 56.99, 'Authentic XI', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Manchester United Third Jersey 2023/24', 199.99, 'Nike', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Man City Mini Pennant', 15.99, 'Umbro', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Inter Miami Away Jersey 2019/20', 180.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Inter Miami Water Bottle', 145.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Mizuno Speedportal.1', 221.99, 'Mizuno', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Man City Away Jersey 2016/17', 73.99, 'Umbro', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Inter Miami Away Jersey 2016/17', 98.99, 'Authentic XI', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Arsenal Third Jersey 2024/25', 211.99, 'Nike', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'PSG Mini Pennant', 89.99, 'Umbro', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Real Madrid Retro Jersey 2023/24', 23.99, 'New Balance', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Inter Miami Third Jersey 2016/17', 215.99, 'Puma', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (18, 'Arsenal Third Jersey 2022/23', 151.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Authentic XI Future 7 FG', 20.99, 'Authentic XI', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Copa Pure', 125.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Manchester United Mini Pennant', 155.99, 'Authentic XI', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Manchester United Third Jersey 2024/25', 28.99, 'Mizuno', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Authentic XI Speedportal.1', 131.99, 'Authentic XI', '2021/22', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Juventus Shin Guards', 107.99, 'New Balance', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'LA Galaxy Water Bottle', 41.99, 'New Balance', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Bayern Munich Wristband Set', 55.99, 'Mizuno', '2016/17', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Manchester United Retro Jersey 2021/22', 142.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Man City Mini Pennant', 100.99, 'New Balance', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'Man City Home Jersey 2024/25', 73.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (17, 'New Balance Future 7 FG', 235.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'LA Galaxy Mini Pennant', 76.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (1, 'Inter Miami Third Jersey 2013/14', 231.99, 'Nike', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'New Balance Future 7 FG', 124.99, 'New Balance', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Arsenal Retro Jersey 2013/14', 227.99, 'Adidas', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'Liverpool Pin Badge Set', 51.99, 'Nike', '2023/24', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Arsenal Home Jersey 2024/25', 27.99, 'Puma', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Man City Away Jersey 2013/14', 132.99, 'Puma', '2013/14', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'LA Galaxy Wristband Set', 102.99, 'Adidas', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'LA Galaxy Home Jersey 2016/17', 25.99, 'Mizuno', '2016/17', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'Inter Miami Away Jersey 2021/22', 151.99, 'Mizuno', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Umbro Future 7 FG', 233.99, 'Umbro', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'PSG Home Jersey 2024/25', 159.99, 'Adidas', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Juventus Club Scarf', 158.99, 'Puma', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (4, 'PSG Captain's Armband', 150.99, 'Puma', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Inter Miami Retro Jersey 2024/25', 32.99, 'Authentic XI', '2024/25', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (15, 'PSG Retro Jersey 2019/20', 112.99, 'Authentic XI', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Adidas Future 7 AG', 130.99, 'Adidas', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'LA Galaxy Home Jersey 2019/20', 227.99, 'Adidas', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Nike Speedportal.1', 86.99, 'Nike', '2023/24', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Real Madrid Shin Guards', 163.99, 'New Balance', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'Manchester United Key Ring', 204.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (10, 'PSG Water Bottle', 96.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Authentic XI Speedportal.1', 22.99, 'Authentic XI', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Manchester United Third Jersey 2023/24', 60.99, 'Authentic XI', '2023/24', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Manchester United Away Jersey 2021/22', 13.99, 'Adidas', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (9, 'Real Madrid Water Bottle', 11.99, 'Nike', '2024/25', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (12, 'PSG Key Ring', 55.99, 'Authentic XI', '2022/23', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'LA Galaxy Club Scarf', 69.99, 'Mizuno', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Puma Phantom GX 2 FG', 230.99, 'Puma', '2022/23', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (7, 'Man City Captain's Armband', 60.99, 'Umbro', '2021/22', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (8, 'Liverpool Away Jersey 2021/22', 77.99, 'Umbro', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (2, 'Real Madrid Third Jersey 2021/22', 68.99, 'Mizuno', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Manchester United Mini Pennant', 190.99, 'New Balance', '2013/14', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Mizuno Future 7 FG', 224.99, 'Mizuno', '2019/20', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (6, 'Bayern Munich Away Jersey 2022/23', 70.99, 'Nike', '2022/23', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'LA Galaxy Pin Badge Set', 108.99, 'Authentic XI', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Liverpool Club Scarf', 33.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (11, 'Liverpool Shin Guards', 64.99, 'Adidas', '2019/20', 'Accessories');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (5, 'Mizuno Copa Pure', 219.99, 'Mizuno', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'Adidas Future 7 FG', 88.99, 'Adidas', '2016/17', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (19, 'Puma Phantom GX 2 FG', 211.99, 'Puma', '2024/25', 'Footwear');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (20, 'Liverpool Home Jersey 2019/20', 38.99, 'Nike', '2019/20', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (13, 'LA Galaxy Away Jersey 2021/22', 76.99, 'Puma', '2021/22', 'Jersey');
INSERT INTO Product (team_id, prod_name, prod_price, prod_brand, prod_season, prod_type) VALUES (14, 'Chelsea Captain's Armband', 236.99, 'Nike', '2021/22', 'Accessories');